title: "YANOTECH: Yet ANOther TECHnical Blog"
author: "Juande Santander-Vela"
theme: jekyll-theme-minimal
# remote_theme: samarsault/texture
baseurl: YANOTECH/
markdown: kramdown
permalink: /:slug
paginate: 2
paginate_path: "/page:num/"
