title: "YANOTECH: Yet ANOther TECHnical Blog"
author: "Juande Santander-Vela"
baseurl: /YANOTECH
# theme: jekyll-theme-minimal
remote_theme: samarsault/texture
markdown: 
show_excerpts: true
permalink: /:slug
paginate: 2
paginate_path: "/page:num/"
texture:
  title: "YANOTECH"
  tagline: Yet ANOther TECHnical Blog
  date_format: "%Y-%m-%d"
  style: blue

  social_links:
    twitter: juandesant
    github:  juandesant
    linkedIn: in/juandesant